schema_version = "1.0.0"

id = "node_quick_maths"
version = "1.0.0"
name = "Node Quick Maths"
tagline = "A fast way to make long math chains in Shader nodes"
maintainer = "Erin MacDonald <zeptofine@gmail.com>"
type = "add-on"

# link to documentation, support, source files, etc
website = "https://github.com/zeptofine/NodeQuickMaths"

# Optional list defined by Blender and server, see:
# https://docs.blender.org/manual/en/dev/advanced/extensions/tags.html
tags = ["Node", "Pipeline", "User Interface", "Geometry Nodes", ]

blender_version_min = "4.2.0"
# Optional: maximum supported Blender version
# blender_version_max = "5.1.0"

# License conforming to https://spdx.org/licenses/ (use "SPDX: prefix)
# https://docs.blender.org/manual/en/dev/extensions/licenses.html
license = [
  "SPDX:GPL-3.0-or-later",
]
# Optional: required by some licenses.
copyright = [
  "2023-2024 Erin MacDonald",
]