[project]
name = "node-quick-maths"
version = "0.1.0"
description = "Add your description here"
dependencies = [
    "blender-stubs>=3.12.27",
]
readme = "README.md"
requires-python = ">= 3.8, <=3.12"

[tool.ruff]
target-version = "py311"
line-length = 120